[package]
name = "strive"
version = "0.1.1"
description = "A calm notebook for mathematical thinking"
authors = ["Strive"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
